Repository atlp-rwanda/ecommerce-app-predators-fe, pull requests merged in 2023-07, with the labels that each got.

#42 #58 #20 Feature:In-app Notifications
  package-lock.json
  src/App.tsx
  src/components/HeaderNav.tsx
  src/components/notification/Notification.tsx
  src/redux/action/NotificationAction.tsx
  src/redux/action/SearchAction.tsx
  src/redux/action/notificationActions.tsx
  src/redux/action/productActions.tsx
  src/redux/reducers/NotificationReducer.tsx
  src/redux/reducers/NotificationSlice.tsx
  src/redux/store/Store.tsx
Labels: Need Review

#37 # 54 recommended product
  src/pages/SearchProductPage.tsx
  src/redux/action/ProductAction.tsx
  src/redux/action/SearchAction.tsx
  src/redux/action/SearchProductAction .tsx
  src/redux/action/UpdateProduct.tsx
  src/redux/action/UserAction.tsx
  src/redux/action/productActions.tsx
  src/redux/action/profileAction.tsx
Labels: Need Review

#46 Feature: Landing Page
  .env
  index.html
  src/assets/images/canon.jpg
  src/assets/images/english.png
  src/components/Admin/AdminSideBar.tsx
  src/components/Admin/UserTable.tsx
  src/components/HeaderNav.tsx
  src/components/cardComponent/Card.tsx
  src/components/carousel/Carousel.tsx
  src/components/category/Category.tsx
  src/components/flashSale/FlashSale.tsx
  src/components/gridProducts/GridProducts.tsx
  src/components/index.tsx
  src/components/mainProduct/MainProduct.tsx
  src/components/navigation/Navigation.tsx
  src/components/news/News.tsx
  src/components/popular/Popular.tsx
  src/components/product_form/Product_form.tsx
  src/components/sidebar/Sidebar.tsx
  src/components/table/Table.tsx
  src/components/table/UserTable.tsx
  src/components/testimony/Testimony.tsx
  src/components/upload/FileHeader.tsx
  src/components/upload/MultipleFileUpload.tsx
  src/components/upload/SingleFileUpload.tsx
  src/components/upload/UploadError.tsx
  src/components/upload/index.tsx
  src/components/vendor/DeleteItem.tsx
  src/dashboard/vendor/VendorPage.tsx
  src/pages/LandingPage.tsx
  src/pages/PasswordExpirationPage.tsx
  src/pages/SearchProductPage.tsx
  src/pages/UpdateProduct.tsx
  src/pages/profile/ProfilePage.tsx
  src/pages/vendor/VendorPage.tsx
  src/pages/viewProduct.tsx
  src/redux/action/UpdateProduct.tsx
  src/redux/action/disableAction.tsx
  src/redux/action/passwordExpirationAction.tsx
  src/redux/reducers/ProfileReducer.tsx
  src/redux/reducers/imageSlice.tsx
  src/redux/reducers/vendorSlice.tsx
  src/redux/store/Store.tsx
  tailwind.config.js
Labels: Need Review

#43 #19 feature: Track order status
  package.json
  src/App.tsx
  src/Layout.tsx
  src/components/__tests__/deleteVendorItem.test.tsx
  src/components/cardComponent/Card.tsx
  src/components/navigation/Navigation.tsx
  src/components/notification/Notification.tsx
  src/components/review/review.tsx
  src/dashboard/admin/admin.tsx
  src/pages/AdminViewUsersPage.tsx
  src/pages/UpdateProduct.tsx
  src/pages/buyer/Orders.tsx
  src/redux/action/OrdersAction.tsx
  src/redux/action/otpAction.tsx
  src/redux/action/passwordExpirationAction.tsx
  src/redux/action/reviewAction.tsx
  src/redux/reducers/OrdersSlice.tsx
  src/redux/reducers/ReviewSlice.tsx
  src/redux/store/Store.tsx
Labels: Need Review

#44 #23 features: Checkout and payment UI
  src/App.tsx
  src/assets/images/Right-side.jpg
  src/assets/images/red_exclamation.png
  src/components/checkout/Dropdown.tsx
  src/components/checkout/Input.tsx
  src/components/checkout/payment.tsx
  src/pages/LoginPage.tsx
  src/pages/checkout/CheckoutPage.tsx
  src/pages/payment/Payment_fail.tsx
  src/pages/payment/Payment_success.tsx
  src/redux/action/NotificationAction.tsx
  src/redux/action/ProductAction.tsx
  src/redux/action/UserAction.tsx
  src/redux/action/notificationActions.tsx
  src/redux/reducers/NotificationReducer.tsx
  src/redux/store/Store.tsx
  src/utils/payment_funcs.tsx
  src/utils/token_funcs.tsx
  src/utils/useCheckout.tsx
  src/utils/useFetch.tsx
  src/utils/useRestCountries.tsx
Labels: Need Review

#56 #100 feature(tests): App
  package-lock.json
  package.json
  src/components/__tests__/AdminAction.test.tsx
  src/components/__tests__/LoginAction.test.tsx
  src/components/__tests__/ResetPassword.test.tsx
  src/components/__tests__/UserActions.test.tsx
  src/components/__tests__/WishlistAction.test.tsx
  src/components/__tests__/notifications.test.tsx
  src/redux/action/WishlistAction.tsx
  src/redux/action/authAction.tsx
Labels: Need Review

#53 feat(landing-page): add integration with the backend
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  src/Layout.tsx
  src/components/Footer.tsx
  src/components/__tests__/profileAction.test.tsx
  src/components/__tests__/sample.test.tsx
  src/components/cardComponent/Card.tsx
  src/components/carousel/Carousel.tsx
  src/components/category/Category.tsx
  src/components/flashSale/FlashSale.tsx
  src/components/gridProducts/GridProducts.tsx
  src/components/mainProduct/MainProduct.tsx
  src/components/navigation/Navigation.tsx
  src/components/popular/Popular.tsx
  src/components/product_form/Product_form.tsx
  src/dashboard/vendor/VendorPage.tsx
  src/mocks/responses/profile.tsx
  src/pages/LandingPage.tsx
  src/pages/SearchProductPage.tsx
  src/pages/profile/ProfilePage.tsx
  src/redux/action/HomeProducts.tsx
  src/redux/action/productActions.tsx
  src/redux/action/profileAction.tsx
  src/redux/reducers/homeProductSlice.tsx
  src/redux/store/Store.tsx
  src/utils/miscFunctions.tsx
  src/utils/test_utils.tsx
Labels: Need Review, Priority

#58 ft-addReview-tests
  package-lock.json
  package.json
  src/components/PlayGame.tsx
  src/components/StaticReview.tsx
  src/components/__tests__/AddReview.test.tsx
  src/components/__tests__/ResetPassword.test.tsx
  src/components/__tests__/UserActions.test.tsx
  src/components/__tests__/WishlistAction.test.tsx
  src/components/productPicture.tsx
  src/components/review/review.tsx
  src/components/sample.tsx
  src/pages/LandingPage.tsx
  src/pages/buyer/Orders.tsx
  src/pages/payment/Payment_fail.tsx
  src/pages/payment/Payment_success.tsx
  src/pages/viewProduct.tsx
  src/redux/action/OrdersAction.tsx
  src/redux/action/reviewAction.tsx
  src/utils/axios.tsx
  src/utils/token_funcs.tsx
  tsconfig.json
Labels: Need Review

#59 otpActions and Carts tests
  src/components/__tests__/cartAction.test.tsx
  src/components/__tests__/otpAction.test.tsx
  src/components/__tests__/profileAction.test.tsx
  src/components/__tests__/sample.test.tsx
Labels: Need Review

#61 #100 feature(App): Fix Protected Routes
  src/App.tsx
  src/dashboard/admin/admin.tsx
  src/pages/LoginPage.tsx
  src/pages/cart/cartData.tsx
  src/redux/reducers/authSlice.tsx
Labels: Need Review

#62 fix the Product by id
  src/components/StaticReview.tsx
  src/components/carousel/Carousel.tsx
  src/components/flashSale/FlashSale.tsx
  src/components/navigation/Navigation.tsx
  src/pages/AddToCart.tsx
  src/pages/LandingPage.tsx
  src/pages/cart/cartData.tsx
  src/pages/viewProduct.tsx
  src/redux/action/ProductAction.tsx
  src/redux/action/cartAction.tsx
  src/redux/reducers/ProductSlice.tsx
  src/redux/reducers/productReducer.tsx
Labels: Ready to merge

#64 fix: fixing image upload on update
  src/components/cardComponent/Card.tsx
  src/components/chat/ChatModal.tsx
  src/components/popular/Popular.tsx
  src/components/table/Table.tsx
  src/pages/LoginPage.tsx
  src/pages/UpdateProduct.tsx
  src/pages/viewProduct.tsx
  src/redux/action/UpdateProduct.tsx
  src/redux/action/productActions.tsx
  src/redux/action/profileAction.tsx
  src/redux/reducers/imageSlice.tsx
Labels: Ready to merge

#65 fix-add-tests
  src/components/__tests__/ HomeProducts.test.tsx
  src/components/__tests__/ ProductAction.test.tsx
  src/components/__tests__/ notificationActions.test.tsx
  src/components/__tests__/ productActions.test.tsx
  src/components/__tests__/CartActions.test.tsx
  src/components/__tests__/OrdersAction.test.tsx
  src/components/__tests__/SearchAction.test.tsx
  src/components/__tests__/disableAction.test.tsx
  src/components/__tests__/passwordExpirationAction.test.tsx
  src/components/navigation/Navigation.tsx
  src/redux/action/passwordExpirationAction.tsx
Labels: Ready to merge
